### ISSUE TITLE
Feat: 프로젝트 오프셋 방식으로 변경 & 로고 변경

### ISSUE THREAD

**Issue by daindaind** [University-MakeUs-Challenge-ProductTeam/Official-Web-FE#13]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

- 수정된 API를 다시 적용하고, UI/UX를 변경합니다.
- 변경된 로고 파일을 적용합니다.

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [ ] 프로젝트 API 오프셋 버전 적용
- [x] 메인 로고 변경
- [x] 구글폼 링크 연결 (소개 - 문의하러 가기)

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

feature/#13

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)

**Comment by dydals3440** [comment]
브랜치명도 대문자로 되어있는데 한 번 소문자로 바꿔주세요~!!!
